(() => {
"use strict";
const OP=({claude:"Claude"})[new URLSearchParams(location.search).get("operator")?.toLowerCase()]||"Codex";
const GOAL="未対応の問い合わせから、ログインできず困っている件を探して、担当を技術担当に変更して保存してください。該当なしなら変更せず終了してください。";
const root=document.querySelector("#lanes"),tpl=document.querySelector("#lane-template"),goal=document.querySelector("#goal"),scenario=document.querySelector("#scenario"),reset=document.querySelector("#reset");let config=null,lanes=[];
const words={normal:{all:"すべて",pending:"未対応だけ表示",back:"一覧へ戻る",save:"変更を保存",tech:"技術担当にする"},changed:{all:"全件を表示",pending:"まだ対応していないもの",back:"問い合わせ一覧へ",save:"担当変更を確定",tech:"技術チームへ振り分け"},missing:{all:"すべて",pending:"未対応だけ表示",back:"一覧へ戻る",save:"変更を保存",tech:"技術担当にする"}};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"})[c]),now=()=>performance.now(),fmt=n=>`${(n/1000).toFixed(1)} 秒`,rid=p=>crypto.randomUUID?.()||`${p}-${Date.now()}`;
function abortAll(reason){lanes.forEach(l=>l.running&&stop(l,reason,false));}
async function load(){abortAll("画面を切り替えました");root.replaceChildren();lanes=[];config=null;goal.disabled=true;reset.disabled=true;try{const r=await fetch(`/api/config?scenario=${encodeURIComponent(scenario.value)}`);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d.tickets))throw Error("tickets がありません");config={...d,scenario:scenario.value,goal:d.goal||GOAL};goal.value=config.goal;goal.readOnly=true;goal.title="独立検証は既定の依頼専用です";build();document.querySelector(".legend-op").textContent=OP;}catch(e){goal.value="設定を読み込めません";root.innerHTML=`<section class="api-error"><h2>実験を開始できません</h2><p>設定APIに接続できませんでした：${esc(e.message)}。架空データでは実測と検証が混ざるため、代替データでは実行しません。</p></section>`;}finally{goal.disabled=!config;reset.disabled=false;}}
function lane(kind,title,accent){const n=tpl.content.firstElementChild.cloneNode(true);n.style.setProperty("--accent",accent);n.querySelector(".lane-kind").textContent=kind==="jev"?"JEVが選ぶ → コードが押す":`${OP}が画面を見て、考えて、押す`;n.classList.add(`lane-${kind}`);n.querySelector(".lane-title").textContent=title;n.querySelector(".start").textContent=kind==="jev"?"JEVに任せる":`${OP}計測開始`;n.querySelector(".request-label").textContent=kind==="jev"?"JEV判断回数":"ブラウザー操作数";root.append(n);const l={kind,node:n,tickets:structuredClone(config.tickets),original:structuredClone(config.tickets),view:"list",filter:"all",selected:null,draft:null,saved:new Set(),running:false,start:null,timer:null,actions:0,calls:0,requestMs:0,history:[],runId:null,controller:null,internal:false,endReason:"",terminalChoice:null,result:null,recorded:false,pairs:new Set(),model:null,usage:[]};n.querySelector(".start").onclick=()=>kind==="jev"?runJev(l):startCodex(l);n.querySelector(".stop").onclick=()=>stop(l,"ユーザーが停止",kind!=="jev");n.querySelector(".verify").onclick=()=>{if(l.running)stop(l,"結果を確認",false);verify(l);record(l);};n.querySelector(".work-area").onclick=e=>onAction(l,e);l.stepAt=[];l.lastConf=null;render(l);renderSteps(l);spot(l,"",kind==="jev"?"開始を待っています":"開始を待っています");return l;}
function build(){lanes.push(lane("codex",`${OP}のみ`,"#3166d7"),lane("jev",OP==="Codex"?"Codex + JEV":"JEV ＋ 実行コード","#007d78"));}
const STEPS=["案件を開く","担当を選ぶ","保存する","完了"];
function stepOf(id){return id.startsWith("open-")?0:id.startsWith("assign-")?1:id==="save-ticket"?2:-1;}
function renderSteps(l){const who=l.kind==="jev"?"JEV":OP;l.node.querySelector(".steps").innerHTML=STEPS.map((s,i)=>{const a=l.stepAt[i];return `<li class="${a?"on":""}"><span class="n">${i+1}</span><span class="s">${s}</span><small>${a?`${esc(a.who)}${a.conf!=null?` ${a.conf.toFixed(2)}`:""} ・ +${fmt(a.t)}`:"—"}</small></li>`;}).join("");}
function spot(l,who,what){const b=l.node.querySelector(".spotlight");b.querySelector(".who").textContent=who;b.querySelector(".what").textContent=what;b.classList.remove("pulse");void b.offsetWidth;if(who)b.classList.add("pulse");}
function mark(l,i,who){if(i<0||l.stepAt[i])return;l.stepAt[i]={t:l.start?now()-l.start:0,who,conf:l.kind==="jev"?l.lastConf:null};renderSteps(l);}
function state(l,s){l.node.querySelector(".run-state").textContent=s;}function metrics(l){l.node.querySelector(".wall-time").textContent=l.start?fmt(now()-l.start):"0.0 秒";l.node.querySelector(".request-count").textContent=l.kind==="jev"?`${l.calls} 回 / ${l.requestMs}ms`:`${l.actions} 回`;}
function log(l,label,role=l.kind==="jev"?"JEV":OP){const box=l.node.querySelector(".log"),li=document.createElement("li"),t=document.createElement("time");t.textContent=`+${fmt(l.start?now()-l.start:0)}`;li.append(t,`${role}　${label}`);box.append(li);l.history.push({elapsed_ms:Math.round(l.start?now()-l.start:0),role,label});}
function render(l){const b=l.node.querySelector(".work-area"),w=words[config.scenario];if(l.view==="list"){const list=l.tickets.filter(t=>l.filter!=="pending"||t.status==="未対応");b.innerHTML=`<div class="view-title"><h3>問い合わせ</h3><p>表示：${l.filter==="pending"?"未対応":"すべて"} ／ ${list.length}件</p></div><div class="filters">${config.scenario==="changed"?`<button class="action ${l.filter==="pending"?"active":""}" data-action-id="filter-pending">${w.pending}</button><button class="action ${l.filter==="all"?"active":""}" data-action-id="filter-all">${w.all}</button>`:`<button class="action ${l.filter==="all"?"active":""}" data-action-id="filter-all">${w.all}</button><button class="action ${l.filter==="pending"?"active":""}" data-action-id="filter-pending">${w.pending}</button>`}</div><ul class="ticket-list">${list.length?list.map(t=>`<li><button class="ticket ${l.selected===t.id?"selected":""}" data-action-id="open-${esc(t.id)}"><span class="ticket-line"><b>${esc(t.subject)}</b><span class="status">${esc(t.status)}</span></span><p class="ticket-preview">${esc(t.body)}</p><small>${esc(t.id)}　担当：${esc(t.assignee)}</small></button></li>`).join(""):`<li class="message">表示できる問い合わせはありません</li>`}</ul>`;return;}const t=l.tickets.find(x=>x.id===l.selected);if(!t){l.view="list";render(l);return;}const choice=l.draft??t.assignee,controls=config.scenario==="changed"?`<button class="action" data-action-id="assign-support">サポート窓口に振り分け</button><button class="action ${choice==="技術担当"?"selected":""}" data-action-id="assign-technical">${w.tech}</button>`:`<button class="action ${choice==="技術担当"?"selected":""}" data-action-id="assign-technical">${w.tech}</button><button class="action" data-action-id="assign-sales">営業担当にする</button>`;b.innerHTML=`<div class="detail"><button class="action" data-action-id="back-list">← ${w.back}</button><div><p class="kicker">${esc(t.id)} / ${esc(t.status)}</p><h3>${esc(t.subject)}</h3></div><p>${esc(t.body)}</p><dl><dt>保存済み担当</dt><dd>${esc(t.assignee)}</dd><dt>選択中の担当</dt><dd>${esc(choice)}</dd><dt>保存状態</dt><dd>${l.saved.has(t.id)?"保存完了":"未保存"}</dd></dl><div><p class="kicker">担当を選択</p><div class="assign">${controls}</div></div><div class="save-row"><span>選択中：<b>${esc(choice)}</b></span><button class="action" data-action-id="save-ticket">${w.save}</button></div></div>`;}
function onAction(l,e){const b=e.target.closest("button[data-action-id]");if(!b||!l.running||(l.kind==="jev"&&!l.internal))return;act(l,b.dataset.actionId,b.textContent.trim(),l.kind==="jev"?"JEV":OP);}
function act(l,id,label,role){if(id==="filter-pending")l.filter="pending";else if(id==="filter-all")l.filter="all";else if(id.startsWith("open-")){l.selected=id.slice(5);l.view="detail";l.draft=null;}else if(id==="back-list"){l.view="list";l.draft=null;}else if(id.startsWith("assign-"))l.draft=id==="assign-technical"?"技術担当":id==="assign-sales"?"営業担当":"サポート窓口";else if(id==="save-ticket"){const t=l.tickets.find(x=>x.id===l.selected);if(t&&l.draft!==null){t.assignee=l.draft;l.saved.add(t.id);}}l.actions++;log(l,label,role);render(l);metrics(l);if(l.kind!=="jev")state(l,`${OP}が操作中（${l.actions}回目）`);mark(l,stepOf(id),role);spot(l,role==="JEV"?"コードが押した":`${role}が押した`,label.split(/未対応|対応中|完了/)[0].slice(0,24));const w=l.node.querySelector(".work-area");w.classList.remove("pulse");void w.offsetWidth;w.classList.add("pulse");}
function startCodex(l){if(l.running)return;l.running=true;l.runId=rid("codex");l.start=now();l.node.querySelector(".start").disabled=true;l.node.querySelector(".stop").disabled=false;goal.disabled=true;state(l,`${OP}が画面操作するのを待機中`);spot(l,OP,"画面を見て考えています…");log(l,"計測開始","計測");l.timer=setInterval(()=>metrics(l),100);}
function stop(l,reason,shouldRecord){if(!l.running)return;l.running=false;l.endReason=reason;l.controller?.abort();clearInterval(l.timer);l.node.querySelector(".stop").disabled=true;state(l,reason);log(l,reason,"計測");metrics(l);if(!lanes.some(x=>x.running))goal.disabled=false;if(shouldRecord)record(l);}
function visible(b){return !b.disabled&&b.getClientRects().length>0;}function observe(l){const w=l.node.querySelector(".work-area");return{text:w.innerText.replace(/\s+/g," ").trim(),controls:[...w.querySelectorAll("button[data-action-id]")].filter(visible).map(b=>({id:b.dataset.actionId,label:b.textContent.trim()}))};}
function domClick(l,id){const b=[...l.node.querySelectorAll(".work-area button[data-action-id]")].find(x=>x.dataset.actionId===id&&visible(x));if(!b)return false;l.internal=true;b.classList.add("jev-choice");b.click();l.internal=false;return true;}
async function runJev(l){if(l.running)return;l.running=true;l.start=now();l.runId=rid("jev");l.controller=new AbortController();l.node.querySelector(".start").disabled=true;l.node.querySelector(".stop").disabled=false;goal.disabled=true;state(l,"JEVが次の操作を判断中");log(l,"実行開始","JEV");l.timer=setInterval(()=>metrics(l),100);while(l.running&&l.calls<12){const ob=observe(l);if(!ob.controls.length){stop(l,"操作候補がありません",false);break;}let d,s=now();try{const r=await fetch("/api/decide",{method:"POST",signal:l.controller.signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({run_id:l.runId,goal:goal.value,observation:ob,history:l.history,step:l.calls+1})});if(!r.ok)throw Error(`JEV API HTTP ${r.status}`);d=await r.json();}catch(e){if(e.name!=="AbortError"){log(l,`ネットワークエラー：${e.message}`,"JEV");stop(l,"JEVへ接続できません",false);}break;}if(!l.running)break;l.model=d.model||l.model;l.usage.push(d.usage??null);l.requestMs+=Math.round(now()-s);l.calls++;metrics(l);const id=String(d.choice||"").trim(),cf=Number(d.confidence||0),note=`${id||"不明"}（確信度 ${cf.toFixed(2)} / ${d.elapsed_ms??"?"}ms）`;if(cf<.65){log(l,`保留：${note}`,"JEV");stop(l,"確信度が不足しています",false);break;}if(["NONE","STOP","DONE"].includes(id)){l.terminalChoice=id;log(l,`判断：${note}`,"JEV");l.lastConf=cf;spot(l,`JEVが選んだ（確信度 ${cf.toFixed(2)}）`,id==="DONE"?"完了":id==="NONE"?"該当なし":"停止");stop(l,id==="NONE"?"該当なしで終了":id==="DONE"?"JEVが完了を選択":"JEVが停止を選択",false);break;}const pair=`${ob.text}\n${id}`;if(l.pairs.has(pair)){log(l,`停止：同じ画面で同じ操作を再選択 (${id})`,"JEV");stop(l,"同じ判断を繰り返しました",false);break;}l.pairs.add(pair);log(l,`判断：${note}`,"JEV");l.lastConf=cf;spot(l,`JEVが選んだ（確信度 ${cf.toFixed(2)}）`,(ob.controls.find(c=>c.id===id)?.label||id).split(/未対応|対応中|完了/)[0].slice(0,24));if(!domClick(l,id)){log(l,`無効な選択：${note}`,"JEV");stop(l,"現在画面にない操作を選びました",false);break;}}if(l.running&&l.calls>=12)stop(l,"判断回数の上限に達しました",false);verify(l);record(l);}
function verify(l){const expected=l.original.find(t=>t.status==="未対応"&&/ログイン/.test(`${t.subject} ${t.body}`)),out=l.node.querySelector(".verification");let result;if(!expected){const validEnd=l.kind==="codex"?l.endReason==="結果を確認":["NONE","DONE"].includes(l.terminalChoice);result=JSON.stringify(l.tickets)===JSON.stringify(l.original)&&validEnd?"該当なしで変更なし":!validEnd?"未完了：該当なしの確認を完遂していません":"不一致：該当なしなのに変更されています";}else{const actual=l.tickets.find(t=>t.id===expected.id),want={...expected,assignee:"技術担当"},target=JSON.stringify(actual)===JSON.stringify(want),others=l.tickets.every(t=>t.id===expected.id||JSON.stringify(t)===JSON.stringify(l.original.find(x=>x.id===t.id)));const validEnd=l.kind==="codex"?l.endReason==="結果を確認":l.terminalChoice==="DONE";result=target&&others&&l.saved.has(expected.id)&&validEnd?"成功：対象だけ保存済み":target&&others&&!l.saved.has(expected.id)?"未完了：担当は見えても保存されていません":!validEnd?"未完了：状態は合っても実行を完遂していません":!l.saved.has(expected.id)?"未完了：依頼どおりの状態になっていません":"不一致：対象外または別の項目が変わっています";}l.result=result;out.textContent=result;if(/^(成功|該当なしで変更なし)/.test(result)){mark(l,3,l.kind==="jev"?"JEV":OP);l.node.classList.add("is-success");l.node.querySelector(".done-banner").textContent=l.kind==="jev"?`✓ 完了　JEVが${l.calls}回選び、コードが${l.actions}回押した`:`✓ 完了　${OP}が自分で見て${l.actions}回押した`;}out.className=`verification ${/^(成功|該当なしで変更なし)/.test(result)?"success":"fail"}`;return result;}
async function record(l){if(!l.runId||l.recorded)return;l.recorded=true;const p={run_id:l.runId,lane:l.kind,scenario:config.scenario,goal:goal.value,elapsed_ms:Math.round(l.start?now()-l.start:0),calls:l.calls,request_ms:l.requestMs,actions:l.actions,history:l.history,original_tickets:l.original,final_tickets:l.tickets,result:l.result,end_reason:l.endReason,terminal_choice:l.terminalChoice,model:l.kind==="jev"?l.model:`${OP} UI操作`,usage:l.kind==="jev"?l.usage:{browser_actions:l.actions}};try{const r=await fetch("/api/record",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});if(!r.ok)throw Error(`HTTP ${r.status}`);}catch(e){const o=l.node.querySelector(".verification");o.textContent=`${l.result||"未検証"} ／ 記録送信エラー：${e.message}`;o.className="verification fail";}}
scenario.onchange=load;reset.onclick=load;load();
})();
